name: Run automated tests
on:
  push:
    paths-ignore:
      - '**.md'
      - '.git*'


jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OS packages for Python
        run: sudo apt install python3-venv
        if: matrix.os == 'ubuntu-latest'

      - name: Specify Python command
        run: echo "::set-env name=PY::python"
        if: matrix.os == 'windows-latest'
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env

      - name: Run automated tests
        run:  make -C tests test-verbose

  cygwin:
    name: windows-cygwin
    runs-on: windows-latest
    env:
      CYGWIN_SETUP_URL: https://cygwin.com/setup-x86_64.exe
      CYGWIN_MIRROR: http://cygwin.mirrors.pair.com/
      CYGWIN_ROOT: $GITHUB_WORKSPACE/cygwin/
      CYGWIN_PACKAGES: make,python3,git,bash
    steps:
      - uses: actions/checkout@v1
      - name: Fetch Cygwin installer
        run: |
          mkdir -p "$CYGWIN_ROOT/packages"
          curl -o "$CYGWIN_ROOT/setup.exe" -sSL "$CYGWIN_SETUP_URL"
        shell: bash
      - name: Install Cygwin environment
        run: >-
          "$CYGWIN_ROOT/setup.exe"
          --quiet-mode
          --no-desktop
          --download
          --local-install
          --no-verify
          --site "$CYGWIN_MIRROR"
          --local-package-dir "$CYGWIN_ROOT/packages"
          --root "$CYGWIN_ROOT"
      - name: Install Cygwin packages
        run: >-
          "$CYGWIN_ROOT/setup.exe"
          --quiet-mode
          --no-desktop
          --download
          --local-install
          --no-verify
          --site "$CYGWIN_MIRROR"
          --local-package-dir "$CYGWIN_ROOT/packages"
          --root "$CYGWIN_ROOT"
          --packages "$CYGWIN_PACKAGES"
      - name: Run automated tests
        run:  make -C tests test-verbose
        shell: $CYGWIN_ROOT/bin/bash.exe --noprofile --norc -eo pipefail {0}
