name: Check for common errors
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install OS packages for Python
        run: sudo apt install python3-venv
      - name: Run automated release tests
        run:  make -C tests test
