name: Check for common errors
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run automated release tests
        run:  make -C tests test
